# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/122dFmFjH49Cb6pAt5hPinnkPfNh5kO5b
"""

import pandas as pd
import streamlit as st
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import SVC

# Importing augmented Training data
# Load the training data from a local file or another source
traindata = pd.read_csv("https://drive.google.com/file/d/1ZDOXYMSUzUPA1lmN23j_gCbFfy6ZkqF2/view?usp=share_link")

# Drop duplicates
traindata = traindata.drop_duplicates(subset='sentence')

# Split the data into training and test sets
X_train = traindata['sentence']
y_train = traindata['difficulty']

# Preprocess the data
vectorizer = CountVectorizer()
X_train = vectorizer.fit_transform(X_train)

# Create a SVM object
svm = SVC()

# Test the SVM model with the best hyperparameters
svm_best = SVC(C=20, kernel='rbf', gamma='scale')
svm_best.fit(X_train, y_train)

# Streamlit app code
st.title("French Phrase Classifier")

# Prompt the user for input
user_input = st.text_input("Type a French phrase you want to classify:")

# Display the user input
st.write("You entered:", user_input)

# Perform classification and display the prediction
X_test_submission = vectorizer.transform([user_input])
testdata_pred = svm_best.predict(X_test_submission)

st.write("Prediction:", testdata_pred)



"""end"""

